---

- name: check if security updates are available
  become: yes
  ignore_errors: "{{ not check_security_updates_fail_if_unpatched }}"
  ansible.builtin.shell:
    cmd: yum --security check-update --quiet
    warn: false
  register: check_security_updates_result

- name: set fact regarding if security updates are necessary or not
  ansible.builtin.set_fact:
    check_security_updates_needed: "{{ check_security_updates_result.rc == 100 }}"

- name: print variable
  ansible.builtin.debug:
    var: check_security_updates_needed
    verbosity: 1