---

- name: check if security updates are available # noqa command-instead-of-module
  become: yes
  ignore_errors: "{{ not check_security_updates_fail_if_unpatched }}"
  ansible.builtin.command:
    cmd: yum --security check-update --quiet
  register: check_security_updates_result
  changed_when: no

- name: set fact regarding if security updates are necessary or not
  ansible.builtin.set_fact:
    check_security_updates_needed: "{{ check_security_updates_result.rc == 100 }}"

- name: print variable
  ansible.builtin.debug:
    var: check_security_updates_needed
    verbosity: 1